development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  hostname: localhost
  database: plonk
  pool: 5
  username: root
  password:
    
cucumber:
  <<: *test
